### ISSUE TITLE
NOT operator

### ISSUE THREAD

**Issue by filmerjarred** [peebles/json-lucene-like-query#1]
Hey,

This library is a god send for our use case, just having some trouble with the NOT operator. As per our understanding:
`
JSON.query([{a:1}, {a:2}], 'NOT a:1')
`
should return [{a:2}], yet it returns [{a:1}]?

happy to make a PR with some bullet point guidance if needed

**Comment by peebles** [comment]
Looks like this works:

    > JSON.query([{a:1}, {a:2}], '-a:1')
    [ { a: 2 } ]

According to [this document](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#NOT), the standalone NOT is not a valid expression:

Comment?

**Comment by filmerjarred** [comment]
`a NOT 1` will still return both items, but the - operator does work, and should fulfill our needs. Thanks!
