### ISSUE TITLE
Make grammar available

### ISSUE THREAD

**Issue by cyberwombat** [peebles/json-lucene-like-query#2]
Sounds like a cool project and would love to tweak it with modern Peggy/TS. Do you perchance have the original grammar?  Thanks.

**Comment by peebles** [comment]
Man, its been too long.  You might try searching google for "lucene peg.js".  You might find one of those modules better suited.  Some have PEG lucene grammer files.

**Comment by cyberwombat** [comment]
Ok. Appreciate the response. Thanks.
